-- Personal autostart processes.
--
-- Managed in ~/omarchy_configuration/omarchy-dotfiles and symlinked to
-- ~/.config/hypr/autostart.lua, which hyprland.lua loads via
-- require("hypr.autostart").
--
-- Ported from the pre-quattro autostart.overrides.conf, which stopped being
-- read when Omarchy moved Hyprland config from .conf to Lua.

-- o.exec_on_start is the Lua equivalent of `exec-once =`.
--
-- hyprdynamicmonitors used to be started from here. It now runs as a systemd
-- user service instead, which orders it after graphical-session.target, restarts
-- it on failure, and brings along hyprdynamicmonitors-prepare.service (clears
-- stale `monitor=...,disable` lines at boot). Do not add it back here as well,
-- or two daemons will fight over ~/.config/hypr/monitors.conf:
--   systemctl --user enable --now hyprdynamicmonitors.service \
--                                 hyprdynamicmonitors-prepare.service

-- Kept from the old overrides file, still disabled:
-- o.launch_on_start("cursor")
-- o.exec_on_start(o.launch_webapp("https://caprarobotics.atlassian.net/wiki/home"))
-- o.exec_on_start(o.launch_webapp("https://caprarobotics.atlassian.net/jira/for-you"))
-- o.exec_on_start(o.launch_webapp("https://bitbucket.org/CapraRobotics/workspace/overview/"))
