# Bitbucket
unbind = SUPER SHIFT, G
bindd = SUPER SHIFT, G, Bitbucket, exec, omarchy-launch-webapp "https://bitbucket.org/CapraRobotics/workspace/overview/"

# Jira
bindd = SUPER SHIFT, J, Jira, exec, omarchy-launch-webapp "https://caprarobotics.atlassian.net/jira/for-you"

# Confluence
unbind = SUPER SHIFT, O
bindd = SUPER SHIFT, O, Confluence, exec, omarchy-launch-webapp "https://caprarobotics.atlassian.net/wiki/home"

# Webcams
unbind = SUPER SHIFT, W
bindd = SUPER SHIFT, W, Webcams, exec, omarchy-launch-webapp "https://unifi.ui.com/consoles/0CEA1412855100000000085F228E0000000008D11CE00000000066FE3236:2131503338/protect/dashboard/all"

# Close apps
unbind = SUPER, W
bind = SUPER ALT, W, killactive

# Omarchy menu
unbind = SUPER ALT, SPACE
bindd = SUPER, BACKSPACE, Omarchy menu, exec, omarchy-menu

# VDA commander emulator
bindd = SUPER SHIFT, V, VDA-Commander emulator, exec, ~/omarchy_configuration/emulator/vda_commander_launch.sh
bind = SUPER, E, togglespecialworkspace, emulator

# Launch apps
unbind = SUPER, SPACE
bindd = SUPER, R, Launch apps, exec, omarchy-launch-walker

# Lock screen
bindd = ALT, L, Lock screen, exec, omarchy-lock-screen

# Resize windows
unbind = SUPER CTRL, L
bindd = SUPER CTRL, K, Resize up, exec, hyprctl dispatch resizeactive 0 -100
bindd = SUPER CTRL, J, Resize down, exec, hyprctl dispatch resizeactive 0 100
bindd = SUPER CTRL, H, Resize left, exec, hyprctl dispatch resizeactive -100 0
bindd = SUPER CTRL, L, Resize right, exec, hyprctl dispatch resizeactive 100 0

# Keyboard shortcuts list
unbind = SUPER, K
bindd = SUPER SHIFT, K, Keybindings, exec, omarchy-menu-keybindings


# VIM Style Focus Neighbouring Windows
unbind = SUPER, J
bind = SUPER, h, movefocus, l
bind = SUPER, j, movefocus, d
bind = SUPER, k, movefocus, u
bind = SUPER, l, movefocus, r
#
# Vim swap (your original goal)
bind = SUPER CTRL SHIFT, h, swapwindow, l
bind = SUPER CTRL SHIFT, j, swapwindow, d
bind = SUPER CTRL SHIFT, k, swapwindow, u
bind = SUPER CTRL SHIFT, l, swapwindow, r

# Toggle window split
bind = SUPER, i, togglesplit


# Swap the screenshot binds
unbind = , PRINT
unbind = SHIFT, PRINT
bindd = SHIFT, PRINT, Screenshot with editing, exec, omarchy-cmd-screenshot
bindd = , PRINT, Screenshot to clipboard, exec, omarchy-cmd-screenshot smart clipboard
