# Use:
# hyprctl monitors
# to get the monitors of the current setup.

# Left monitor (laptop)
monitor = eDP-1, 2560x1600@165, 0x350, 1.6

# Center monitor
monitor = HDMI-A-1, 3840x2160@60, 1600x0, 1.6

# Home (Ultrawide LG monitor)
monitor = DP-1, 3840x1600@144, 1600x0, 1.25

# Right monitor (portrait, center aligned)
monitor = DP-3, 3840x2160@60, 4000x-400, 1.6, transform, 3
monitor = DP-2, 3840x2160@60, 4000x-400, 1.6, transform, 3

# Sletvej monitor clsest to the entrance and the test facility. 
monitor = DP-1, 3840x2160@60, 1600x0, 1.6
#
# Sletvej dual monitor setup
monitor = DP-1, 3840x2160@60, 1600x0, 1.6
monitor = HDMI-A-1, 3840x2160@60, 4000x0, 1.6

# This is the configuraiton for all other monitors
monitor=,preferred,auto,1.25
