# To find class names of the open programs:
# hyprctl clients | grep -i class

# Editor
#windowrulev = workspace 1, class:^(cursor)$

# Terminal
#windowrule = workspace 2, class:^(Alacritty|kitty|WezTerm|foot|com.mitchellh.ghostty)$

# Jira, Bitbucket
#windowrule = workspace 3, initialClass: chrome-caprarobotics.atlassian.net__jira_for-you-Default
#windowrule = workspace 3, initialClass: chrome-bitbucket.org__CapraRobotics_workspace_overview_-Default

# Browser
#windowrule = workspace 4, class:^(Google-chrome|google-chrome|Chrome)$

# Lichtblick
#windowrule = workspace 5, class: Lichtblick

# MQTT explorer
#windowrule = workspace 6, class: MQTT-Explorer
#windowrule = tile, class: MQTT-Explorer

# Webcams
#windowrule = workspace 7, initialTitle:^(unifi.ui.com_/consoles/0CEA1412855100000000085F228E0000000008D11CE00000000066FE3236:2131503338/protect/dashboard/all)$

# Confluence
#windowrule = workspace 8, initialClass: chrome-bitbucket.org__CapraRobotics_workspace_overview_-Default

# Spotify
#windowrule = workspace special:scratchpad silent, class:^(Spotify|spotify)$

# Teams
#windowrule = workspace special:scratchpad silent, class:^(chrome-cifhbcnohmdccbgoicgdjpfamggdegmo-Default)$

# Emulator should float to preserve aspect ratio
#windowrule = workspace special:emulator silent, class: Emulator
#windowrule = fullscreen, class: Emulator

# Send remaining windows to workspace 9 (Must be the last windowrule)
#windowrule = workspace 9, class:^(.*)$
